package NewLanguage_extends.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int InputField = 0;
  public static final int OutputField = 1;
  public static final int sample1 = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x77fa14737334526L, 0x9ebf7cbd72b86b80L);
    builder.put(0x3d1ab7b3d0a0af2cL, InputField);
    builder.put(0x3d1ab7b3d0a0af48L, OutputField);
    builder.put(0x3d1ab7b3d09cba50L, sample1);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
