package NewSolution3.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Dimension;

public class map_sample1 extends JFrame {
  private JPanel jpanel = new JPanel();

  public static void main(String[] args) {
    map_sample1 sample = new map_sample1();
    sample.initialize();

  }

  public void initialize() {
    System.out.println("this is in initiliaze method--->");
    this.setTitle("title");
    this.add(jpanel);
    this.setPreferredSize(new Dimension(100, 100));
    this.pack();
    this.setVisible(true);
  }
}
