package NewLanguage_extends.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new InputField_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new OutputField_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new sample1_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x77fa14737334526L, 0x9ebf7cbd72b86b80L, 0x3d1ab7b3d0a0af2cL), MetaIdFactory.conceptId(0x77fa14737334526L, 0x9ebf7cbd72b86b80L, 0x3d1ab7b3d0a0af48L), MetaIdFactory.conceptId(0x77fa14737334526L, 0x9ebf7cbd72b86b80L, 0x3d1ab7b3d09cba50L)).seal();
}
