package Sampleshapes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int ColorReference = 3;
  public static final int Shape = 4;
  public static final int Square = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xda65a42c0c5347b5L, 0xa79a1e8fc7d7bd5aL);
    builder.put(0x3d1ab7b3d06e7cdeL, Canvas);
    builder.put(0x3d1ab7b3d06e8166L, Circle);
    builder.put(0x3d1ab7b3d06e8222L, Color);
    builder.put(0x3d1ab7b3d06e8223L, ColorReference);
    builder.put(0x3d1ab7b3d06f8cc9L, Shape);
    builder.put(0x3d1ab7b3d06e8167L, Square);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
