package Shapes_jack.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int ColorReference = 3;
  public static final int Shape = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xad7e527251544f68L, 0xaa7626253b0b1d65L);
    builder.put(0x3d1ab7b3d07c4c5eL, Canvas);
    builder.put(0x3d1ab7b3d07c4c54L, Circle);
    builder.put(0x3d1ab7b3d07ec2f3L, Color);
    builder.put(0x3d1ab7b3d07ec369L, ColorReference);
    builder.put(0x3d1ab7b3d07c4c51L, Shape);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
